/*
 * error_codes.h
 *
 * Created: 23/04/2023 19:32:13
 *  Author: xstejs30
 */ 


#ifndef ERROR_CODES_H_
#define ERROR_CODES_H_

typedef enum {
	ERROR_NONE						=  0,
	ERROR_INVALID_DATA				= -1,
	ERROR_NO_CHANGE					= -2,
	ERROR_ABORTED					= -3,
	ERROR_BUSY						= -4,
	ERROR_SUSPEND					= -5,
	ERROR_IO						= -6,
	ERROR_REQ_FLUSHED				= -7,
	ERROR_TIMEOUT					= -8,
	ERROR_BAD_DATA					= -9,
	ERROR_NOT_FOUND					= -10,
	ERROR_UNSUPPORTED_DEV			= -11,
	ERROR_NO_MEMORY					= -12,
	ERROR_INVALID_ARG				= -13,
	ERROR_BAD_ADDRESS				= -14,
	ERROR_BAD_FORMAT				= -15,
	ERROR_BAD_FRQ					= -16,
	ERROR_DENIED					= -17,
	ERROR_ALREADY_INITIALIZED		= -18,
	ERROR_OVERFLOW					= -19,
	ERROR_NOT_INITIALIZED			= -20,
	ERROR_SAMPLERATE_UNAVAILABLE	= -21,
	ERROR_RESOLUTION_UNAVAILABLE	= -22,
	ERROR_BAUDRATE_UNAVAILABLE		= -23,
	ERROR_PACKET_COLLISION			= -24,
	ERROR_PROTOCOL					= -25,
	ERROR_PIN_MUX_INVALID			= -26,
	ERROR_UNSUPPORTED_OP			= -27,
	ERROR_NO_RESOURCE				= -28,
	ERROR_NOT_READY					= -29,
	ERROR_FAILURE					= -30,
	ERROR_WRONG_LENGTH				= -31,

	ERROR_I2C_NACK					= -41, // I2C Slave returned NACK
	ERROR_I2C_WRITE					= -42, // Error during I2C write process
	ERROR_I2C_READ					= -43, // Error during I2C read process
} ERROR_t;



#endif /* ERROR_CODES_H_ */